#!/usr/bin/env python3
"""State store for the overnight loop.

Single source of truth is loop/state/backlog.json plus loop/state/state.json.
Everything the loop mutates goes through this CLI so a turn can never leave the
state half written: every subcommand rewrites the whole file atomically.

The turn planner lives here too (`plan`), so the supervisor shell script never
has to reason about the queue -- it just runs what this prints.
"""
from __future__ import annotations

import argparse
import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE_DIR = ROOT / "loop" / "state"
BACKLOG = STATE_DIR / "backlog.json"
STATE = STATE_DIR / "state.json"
IDEAS_MD = ROOT / "docs" / "IDEAS.md"

# Status lifecycle. `blocked` is terminal for the night: a human unblocks it.
STATUSES = (
    "proposed",     # drafted, not yet judged
    "accepted",     # judged worth building
    "rejected",     # judged not worth building -- stays as a record
    "parked",       # worth building, but not tonight (too big / needs a human)
    "implemented",  # built on its branch, gates green, not yet on main
    "merged",       # on main
    "blocked",      # tried and failed, or main diverged -- needs a human
)
OPEN_STATUSES = ("proposed", "accepted", "implemented")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _write_json(path: Path, payload) -> None:
    """Atomic write -- a killed turn must never truncate the state."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def load_backlog() -> list[dict]:
    if not BACKLOG.exists():
        return []
    return json.loads(BACKLOG.read_text(encoding="utf-8"))


def load_state() -> dict:
    if not STATE.exists():
        return {"turn": 0, "cost_usd": 0.0, "last_turn_type": None, "started": None}
    return json.loads(STATE.read_text(encoding="utf-8"))


def save_backlog(items: list[dict]) -> None:
    _write_json(BACKLOG, items)


def save_state(state: dict) -> None:
    _write_json(STATE, state)


def _by_status(items: list[dict], status: str) -> list[dict]:
    return [i for i in items if i["status"] == status]


# ----------------------------------------------------------------- turn planner
def plan_turn(items: list[dict], turn: int, deck_every: int) -> str:
    """Which turn type runs next. Pure function of the queue -- no model discretion.

    Order is load-bearing:
      * the deck check comes first so the slide set is never more than
        `deck_every` turns stale, whatever the queue is doing;
      * `merge` outranks `implement` so main keeps moving and the next idea
        branches off a current main (which keeps every merge a fast-forward);
      * `council` fires only when the queue is dry, because it is by far the
        most expensive turn type.
    """
    if turn > 0 and turn % deck_every == 0:
        return "deck"
    if _by_status(items, "implemented"):
        return "merge"
    if _by_status(items, "accepted"):
        return "implement"
    if _by_status(items, "proposed"):
        return "evaluate"
    return "council"


def next_id(items: list[dict]) -> str:
    n = 0
    for i in items:
        try:
            n = max(n, int(i["id"].lstrip("i")))
        except ValueError:
            continue
    return f"i{n + 1:04d}"


# -------------------------------------------------------------------- rendering
def render_ideas(items: list[dict], state: dict) -> str:
    lines = [
        "# IDEAS — the overnight loop's backlog",
        "",
        "Generated by `loop/backlog.py render`. Do not edit by hand; edit the JSON via the CLI.",
        "",
        f"Turn: **{state.get('turn', 0)}** · "
        f"spend so far: **${state.get('cost_usd', 0.0):.2f}** · "
        f"last turn type: **{state.get('last_turn_type') or '—'}**",
        "",
    ]
    for status in STATUSES:
        group = _by_status(items, status)
        if not group:
            continue
        lines.append(f"## {status} ({len(group)})")
        lines.append("")
        for it in group:
            branch = f" · `{it['branch']}`" if it.get("branch") else ""
            lines.append(f"### {it['id']} — {it['title']}{branch}")
            lines.append("")
            lines.append(f"*{it.get('kind', 'unspecified')}* — {it.get('why', '')}")
            lines.append("")
            for note in it.get("notes", []):
                lines.append(f"- turn {note['turn']}: {note['text']}")
            if it.get("notes"):
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# -------------------------------------------------------------------- subcommands
def cmd_plan(args) -> int:
    print(plan_turn(load_backlog(), load_state().get("turn", 0), args.deck_every))
    return 0


def cmd_add(args) -> int:
    items = load_backlog()
    state = load_state()
    idea = {
        "id": next_id(items),
        "title": args.title,
        "kind": args.kind,
        "why": args.why,
        "status": "proposed",
        "branch": None,
        "created_turn": state.get("turn", 0),
        "notes": [],
    }
    items.append(idea)
    save_backlog(items)
    print(idea["id"])
    return 0


def cmd_set(args) -> int:
    items = load_backlog()
    turn = load_state().get("turn", 0)
    for it in items:
        if it["id"] != args.id:
            continue
        if args.status:
            it["status"] = args.status
        if args.branch:
            it["branch"] = args.branch
        if args.note:
            it.setdefault("notes", []).append({"turn": turn, "text": args.note})
        save_backlog(items)
        print(f"{it['id']} -> {it['status']}")
        return 0
    print(f"no such id: {args.id}")
    return 1


def cmd_list(args) -> int:
    items = load_backlog()
    if args.status:
        items = _by_status(items, args.status)
    if args.json:
        print(json.dumps(items, indent=2, ensure_ascii=False))
        return 0
    if not items:
        print("(empty)")
        return 0
    for it in items:
        print(f"{it['id']}  {it['status']:<12} {it.get('kind', ''):<14} {it['title']}")
    return 0


def cmd_render(args) -> int:
    items, state = load_backlog(), load_state()
    IDEAS_MD.parent.mkdir(parents=True, exist_ok=True)
    IDEAS_MD.write_text(render_ideas(items, state), encoding="utf-8")
    print(str(IDEAS_MD.relative_to(ROOT)))
    return 0


def cmd_turn(args) -> int:
    state = load_state()
    if args.bump:
        state["turn"] = state.get("turn", 0) + 1
    if args.type:
        state["last_turn_type"] = args.type
    if state.get("started") is None:
        state["started"] = _now()
    state["updated"] = _now()
    save_state(state)
    print(state["turn"])
    return 0


def cmd_cost(args) -> int:
    state = load_state()
    state["cost_usd"] = round(state.get("cost_usd", 0.0) + args.add, 4)
    save_state(state)
    print(f"{state['cost_usd']:.4f}")
    return 0


def cmd_stats(args) -> int:
    items, state = load_backlog(), load_state()
    counts = {s: len(_by_status(items, s)) for s in STATUSES if _by_status(items, s)}
    print(json.dumps({"turn": state.get("turn", 0),
                      "cost_usd": state.get("cost_usd", 0.0),
                      "open": sum(len(_by_status(items, s)) for s in OPEN_STATUSES),
                      "counts": counts}, indent=2))
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("plan", help="print the turn type that should run next")
    sp.add_argument("--deck-every", type=int, default=5)
    sp.set_defaults(func=cmd_plan)

    sp = sub.add_parser("add", help="add a proposed idea")
    sp.add_argument("--title", required=True)
    sp.add_argument("--why", required=True)
    sp.add_argument("--kind", default="analysis",
                    choices=["analysis", "code", "presentation", "infra", "evaluation"])
    sp.set_defaults(func=cmd_add)

    sp = sub.add_parser("set", help="change an idea's status / branch, or append a note")
    sp.add_argument("--id", required=True)
    sp.add_argument("--status", choices=STATUSES)
    sp.add_argument("--branch")
    sp.add_argument("--note")
    sp.set_defaults(func=cmd_set)

    sp = sub.add_parser("list")
    sp.add_argument("--status", choices=STATUSES)
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=cmd_list)

    sp = sub.add_parser("render", help="rewrite docs/IDEAS.md from the JSON")
    sp.set_defaults(func=cmd_render)

    sp = sub.add_parser("turn", help="bump the turn counter / record the turn type")
    sp.add_argument("--bump", action="store_true")
    sp.add_argument("--type")
    sp.set_defaults(func=cmd_turn)

    sp = sub.add_parser("cost", help="accumulate spend")
    sp.add_argument("--add", type=float, required=True)
    sp.set_defaults(func=cmd_cost)

    sp = sub.add_parser("stats")
    sp.set_defaults(func=cmd_stats)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
